-- Case when
-- 1. How can you display each student along with a readable gender label (Male, Female, or Other) instead of numeric values?
select *, Case gender when 1 then ' Male' when 0 then 'Female' else 'Other' end as [Gender] from TStudent 

-- 2. How can you assign letter grades (A, B, C) to students based on their numeric grade values?
select *, 
	case  
	when grade >= 16 then 'A'  
	when grade >= 15 then 'B' 
	else 'C' 
	end 
 from TCourse_Student  

 


-- If
-- 3. How can you check whether any enrollments exist for course C91, and return either the enrollments for C101 or the message “No Student”?
if (Select count(Code_Course) from TCourse_Student where Code_Course ='C91') > 0 
Begin 
	Select * from TCourse_Student where Code_Course ='C101' 
end 
Else 
	Select 'No Student' as 'Notification' 
 

-- Variables
-- 4. How can you store a course code in a variable by looking up a course standard, and then use that variable to query enrollments?
Declare @Code_Course varchar(10) ; 
set  @Code_Course = (select top 1 code_course from TCourses where Code_Standard = '13960101') 
Select * from TCourse_Student where Code_Course = @Code_Course 


-- 5. How can you assign a course code to a variable using a SELECT statement and then fetch all enrollments for that course?
Declare @Code_Course varchar(10) ; 
select top 1  @Code_Course= code_course from TCourses where Code_Standard = '13960101' 
Select * from TCourse_Student where Code_Course = @Code_Course 


-- System Variables
-- sql version
-- 6. How can you check the current SQL Server version?
SELECT @@VERSION;    
-- active transaction
-- 7. How can you see the number of active transactions?
SELECT @@TRANCOUNT;  
-- row count
-- 8. How can you find out how many rows were affected by the last query?
SELECT @@ROWCOUNT;      
-- last insrted identity
-- 9. How can you retrieve the identity value generated by the most recent INSERT?
SELECT @@IDENTITY;       
-- 10. How can you insert a new teacher and immediately return the auto-generated teacher ID?
Insert into dbo.TTeacher Select 'Ben', 'KullumnBerg', '2012-09-09', 'Python', 'B.Kull@example.com', '077111111111', 'London Kings way' 
Select @@IDENTITY as [code_techer]
 