-- Case when
-- 1. How can you display each student along with a readable gender label (Male, Female, or Other) instead of numeric values?
SELECT *,
  CASE gender WHEN 1 THEN 'Male' WHEN 0 THEN 'Female' ELSE 'Other' END AS [Gender]
FROM student;

-- 2. How can you assign letter grades (A, B, C) to students based on their numeric grade values?
SELECT *,
  CASE
    WHEN grade >= 16 THEN 'A'
    WHEN grade >= 15 THEN 'B'
    ELSE 'C'
  END AS letterGrade
FROM courseStudent;

-- If
-- 3. How can you check whether any enrollments exist for course C91, and return either the enrollments for C101 or the message “No Student”?
IF (SELECT COUNT(courseId) FROM courseStudent WHERE courseId = 'C91') > 0
BEGIN
  SELECT * FROM courseStudent WHERE courseId = 'C101';
END
ELSE
  SELECT 'No Student' AS [Notification];

-- Variables
-- 4. How can you store a course code in a variable by looking up a course standard, and then use that variable to query enrollments?
DECLARE @courseId VARCHAR(10);
SET @courseId = (SELECT TOP 1 courseId FROM course WHERE standardCode = '13960101');
SELECT * FROM courseStudent WHERE courseId = @courseId;

-- 5. How can you assign a course code to a variable using a SELECT statement and then fetch all enrollments for that course?
DECLARE @courseId2 VARCHAR(10);
SELECT TOP 1 @courseId2 = courseId FROM course WHERE standardCode = '13960101';
SELECT * FROM courseStudent WHERE courseId = @courseId2;

-- System Variables
-- sql version
-- 6. How can you check the current SQL Server version?
SELECT @@VERSION;
-- active transaction
-- 7. How can you see the number of active transactions?
SELECT @@TRANCOUNT;
-- row count
-- 8. How can you find out how many rows were affected by the last query?
SELECT @@ROWCOUNT;
-- last inserted identity
-- 9. How can you retrieve the identity value generated by the most recent INSERT?
SELECT @@IDENTITY;

-- 10. How can you insert a new teacher and immediately return the auto-generated teacher ID?
INSERT INTO dbo.teacher (firstName, lastName, hireDate, subject, email, phone, address)
SELECT 'Ben', 'KullumnBerg', '2012-09-09', 'Python', 'B.Kull@example.com', '077111111111', 'London Kings Way';
SELECT @@IDENTITY AS [teacherId];
